# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e23bd4807056ede76171e91033ab38a7cd8f2db94bdd128c88bcf510a01f7a50f941320c69538390e4f3547368f1070f6b1e6cb2e3343fbb8ec0b9504dc0d3

test:
  secret_key_base: aabfc119b8aa23da772d823c4fc1746016b26fc1cc0e50f7b079469410371b4b97a0e183189a075c15740271f8d769f84eed26f7f821b7c528d58f2c8df2df40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
